# -*- coding: utf-8 -*-
"""pipeline

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l7H5PpXCW_kiPE2ysZLDaKOdoQVDYM_B
"""

from pathlib import Path

from extract.extract_data import extract_data

from transform.transform_data import (
    clean_column_names,
    filter_valid_departments,
    filter_population_period,
    reshape_population_2005_2017,
    reshape_population_2018_2050,
    combine_population,
    build_age_groups,
    aggregate_population_by_age_group,
    filter_compatible_age_groups,
    aggregate_suicide_cases,
    integrate_population_cases,
    calculate_indicators,
    add_department_names,
    validate_final_table
)

from load.load_data import load_data


def main():
    # 1. RUTAS DEL PROYECTO
    base_dir = Path(__file__).resolve().parent

    raw_dir = base_dir / "data" / "raw"
    processed_dir = base_dir / "data" / "processed"

    print("=" * 70)
    print("INICIO DEL PIPELINE ETL")
    print("=" * 70)

    # 2. EXTRACT
    print("\n[1/4] EXTRACT")

    df_suic, df_pob1, df_pob2 = extract_data(raw_dir)

    print(f"INMLCF: {df_suic.shape}")
    print(f"DANE 2005-2017: {df_pob1.shape}")
    print(f"DANE 2018-2050: {df_pob2.shape}")

    # 3. TRANSFORM - INMLCF
    print("\n[2/4] TRANSFORM - INMLCF")

    df_suic_clean = clean_column_names(df_suic)

    df_suic_valid = filter_valid_departments(
        df_suic_clean
    )

    print(f"Casos originales: {len(df_suic_clean):,}")
    print(f"Casos válidos: {len(df_suic_valid):,}")
    print(
        f"Casos excluidos: "
        f"{len(df_suic_clean) - len(df_suic_valid):,}"
    )

    # 4. TRANSFORM - POBLACIÓN
    print("\n[2/4] TRANSFORM - POBLACIÓN")

    df_pob1_periodo, df_pob2_periodo = (
        filter_population_period(
            df_pob1,
            df_pob2
        )
    )

    pob1_largo = reshape_population_2005_2017(
        df_pob1_periodo
    )

    pob2_largo = reshape_population_2018_2050(
        df_pob2_periodo
    )

    poblacion = combine_population(
        pob1_largo,
        pob2_largo
    )

    poblacion_grupos = build_age_groups(
        poblacion
    )

    pob_grupos = aggregate_population_by_age_group(
        poblacion_grupos
    )

    pob_final = filter_compatible_age_groups(
        pob_grupos
    )

    print(
        f"Población analítica: "
        f"{len(pob_final):,} filas"
    )

    # 5. TRANSFORM - CASOS
    casos = aggregate_suicide_cases(
        df_suic_valid
    )

    print(
        f"Combinaciones con casos: "
        f"{len(casos):,}"
    )

    # 6. INTEGRACIÓN
    print("\n[3/4] INTEGRACIÓN")

    tabla = integrate_population_cases(
        pob_final,
        casos
    )

    tabla = calculate_indicators(
        tabla
    )

    tabla = add_department_names(
        tabla,
        df_pob2_periodo
    )

    # 7. VALIDACIÓN
    print("\nVALIDACIONES")

    validate_final_table(
        tabla
    )

    # 8. LOAD
    print("\n[4/4] LOAD")

    csv_path, db_path = load_data(
        tabla,
        processed_dir
    )

    print(f"CSV generado: {csv_path}")
    print(f"SQLite generado: {db_path}")

    # 9. FINAL
    print("\n" + "=" * 70)
    print("PIPELINE EJECUTADO CORRECTAMENTE")
    print("=" * 70)


if __name__ == "__main__":
    main()