# -*- coding: utf-8 -*-
"""extract_data

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v0cJ8yyCozX9-GJlBVwMLTiiaY1Rewb5
"""

from pathlib import Path
import pandas as pd


def extract_data(raw_dir: Path):
    """
    Carga las tres fuentes originales del proyecto.

    Parameters
    ----------
    raw_dir : Path
        Carpeta donde están los archivos originales.

    Returns
    -------
    tuple
        DataFrames de INMLCF, DANE 2005-2017 y DANE 2018-2050.
    """

    suic_path = raw_dir / "Presuntos_Suicidios._Colombia,_2015-2024..csv"
    pob1_path = raw_dir / "proypoblacion2005-2017.xlsx"
    pob2_path = raw_dir / "proypoblacion2018-2050.xlsx"

    # Verificar que los archivos existan
    for ruta in [suic_path, pob1_path, pob2_path]:
        if not ruta.exists():
            raise FileNotFoundError(f"No se encontró el archivo: {ruta}")

    # Extraer las fuentes
    df_suic = pd.read_csv(suic_path, low_memory=False)
    df_pob1 = pd.read_excel(pob1_path)
    df_pob2 = pd.read_excel(pob2_path)

    return df_suic, df_pob1, df_pob2