# -*- coding: utf-8 -*-
"""transform_data

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u6a_V9srwj3fRVRRtOchWt4io4pvjfBp
"""

import pandas as pd


def clean_column_names(df: pd.DataFrame) -> pd.DataFrame:
    """
    Elimina espacios innecesarios al inicio y final de los nombres
    de las columnas.
    """
    df = df.copy()
    df.columns = df.columns.str.strip()

    return df

def filter_valid_departments(df: pd.DataFrame) -> pd.DataFrame:
    """
    Excluye los registros cuyo código DANE de departamento es 999,
    utilizado por la fuente para representar 'Sin información'.
    """
    df = df.copy()

    return df[df["Código Dane Departamento"] != 999].copy()

def filter_population_period(
    df_pob1: pd.DataFrame,
    df_pob2: pd.DataFrame
) -> tuple[pd.DataFrame, pd.DataFrame]:
    """
    Conserva únicamente el área geográfica Total y los años
    correspondientes al periodo de estudio 2015-2024.
    """

    pob1 = df_pob1[
        (df_pob1["ÁREA GEOGRÁFICA"] == "Total") &
        (df_pob1["AÑO"].between(2015, 2017))
    ].copy()

    pob2 = df_pob2[
        (df_pob2["ÁREA GEOGRÁFICA"] == "Total") &
        (df_pob2["AÑO"].between(2018, 2024))
    ].copy()

    return pob1, pob2

def reshape_population_2005_2017(
    df: pd.DataFrame
) -> pd.DataFrame:
    """
    Convierte la población DANE 2005-2017 de formato ancho a largo.

    Resultado:
    DP | AÑO | sexo | edad | poblacion
    """

    df = df.copy()

    columnas_edad = [
        c for c in df.columns
        if c.startswith("Hombres_") or c.startswith("Mujeres_")
    ]

    largo = df.melt(
        id_vars=["DP", "AÑO"],
        value_vars=columnas_edad,
        var_name="columna_edad",
        value_name="poblacion"
    )

    largo["sexo"] = (
        largo["columna_edad"]
        .str.split("_")
        .str[0]
        .map({
            "Hombres": "Hombre",
            "Mujeres": "Mujer"
        })
    )

    largo["edad"] = (
        largo["columna_edad"]
        .str.extract(r"(\d+)")[0]
        .astype(int)
    )

    largo = largo[
        ["DP", "AÑO", "sexo", "edad", "poblacion"]
    ]

    return largo

def reshape_population_2018_2050(
    df: pd.DataFrame
) -> pd.DataFrame:
    """
    Convierte la población DANE 2018-2050 de formato ancho a largo.

    Resultado:
    DP | AÑO | sexo | edad | poblacion
    """

    df = df.copy()

    columnas_edad = [
        c for c in df.columns
        if c.startswith("Hombres ") or c.startswith("Mujeres ")
    ]

    largo = df.melt(
        id_vars=["DP", "AÑO"],
        value_vars=columnas_edad,
        var_name="columna_edad",
        value_name="poblacion"
    )

    largo["sexo"] = (
        largo["columna_edad"]
        .str.split(" ")
        .str[0]
        .map({
            "Hombres": "Hombre",
            "Mujeres": "Mujer"
        })
    )

    largo["edad"] = (
        largo["columna_edad"]
        .str.extract(r"(\d+)")[0]
        .astype(int)
    )

    largo = largo[
        ["DP", "AÑO", "sexo", "edad", "poblacion"]
    ]

    return largo

def combine_population(
    pob1_largo: pd.DataFrame,
    pob2_largo: pd.DataFrame
) -> pd.DataFrame:
    """
    Combina las dos series de población DANE en una estructura común.
    """

    pob1 = pob1_largo.copy()
    pob2 = pob2_largo.copy()

    pob1["serie_poblacion"] = "DANE_2005_2017"
    pob2["serie_poblacion"] = "DANE_2018_2050"

    poblacion = pd.concat(
        [pob1, pob2],
        ignore_index=True
    )

    return poblacion

def build_age_groups(poblacion: pd.DataFrame) -> pd.DataFrame:
    """
    Agrupa las edades simples de DANE en las categorías utilizadas
    por el INMLCF.

    Incluye temporalmente el grupo 00 a 04 para poder verificar
    la conservación de la población.
    """

    poblacion = poblacion.copy()

    bins = [
        0, 5, 10, 15, 18, 20, 25, 30, 35,
        40, 45, 50, 55, 60, 65, 70, 75, 80, 200
    ]

    etiquetas = [
        "(00 a 04)",
        "(05 a 09)",
        "(10 a 14)",
        "(15 a 17)",
        "(18 a 19)",
        "(20 a 24)",
        "(25 a 29)",
        "(30 a 34)",
        "(35 a 39)",
        "(40 a 44)",
        "(45 a 49)",
        "(50 a 54)",
        "(55 a 59)",
        "(60 a 64)",
        "(65 a 69)",
        "(70 a 74)",
        "(75 a 79)",
        "(80 y más)"
    ]

    poblacion["grupo"] = pd.cut(
        poblacion["edad"],
        bins=bins,
        labels=etiquetas,
        right=False
    )

    return poblacion

def aggregate_population_by_age_group(
    poblacion: pd.DataFrame
) -> pd.DataFrame:
    """
    Agrega la población de edades simples a nivel de grupo de edad,
    conservando departamento, año, sexo y serie poblacional.
    """

    poblacion = poblacion.copy()

    poblacion_grupos = (
        poblacion
        .groupby(
            ["DP", "AÑO", "serie_poblacion", "sexo", "grupo"],
            observed=True
        )["poblacion"]
        .sum()
        .reset_index()
    )

    return poblacion_grupos

def filter_compatible_age_groups(
    poblacion: pd.DataFrame
) -> pd.DataFrame:
    """
    Conserva únicamente los 17 grupos de edad compatibles
    con la clasificación utilizada por el INMLCF.
    """

    poblacion = poblacion.copy()

    poblacion = poblacion[
        poblacion["grupo"].astype(str) != "(00 a 04)"
    ].copy()

    poblacion["grupo"] = poblacion["grupo"].astype(str)

    return poblacion

def aggregate_suicide_cases(
    df: pd.DataFrame
) -> pd.DataFrame:
    """
    Agrega los casos del INMLCF por departamento, año, sexo
    y grupo de edad.
    """

    df = df.copy()

    casos = (
        df.groupby(
            [
                "Código Dane Departamento",
                "Año del hecho",
                "Sexo de la victima",
                "Grupo de Edad Quinquenal"
            ],
            dropna=False
        )
        .size()
        .reset_index(name="casos")
    )

    casos.columns = [
        "DP",
        "AÑO",
        "sexo",
        "grupo",
        "casos"
    ]

    return casos

def integrate_population_cases(
    poblacion: pd.DataFrame,
    casos: pd.DataFrame
) -> pd.DataFrame:
    """
    Integra población y casos mediante la llave:
    DP + AÑO + sexo + grupo.

    Las combinaciones sin casos reciben cero.
    """

    tabla = poblacion.merge(
        casos,
        on=["DP", "AÑO", "sexo", "grupo"],
        how="left",
        validate="one_to_one"
    )

    tabla["casos"] = (
        tabla["casos"]
        .fillna(0)
        .astype(int)
    )

    return tabla

def calculate_indicators(
    tabla: pd.DataFrame
) -> pd.DataFrame:
    """
    Calcula indicadores analíticos de la tabla integrada.

    tasa_x100k:
        Casos por 100.000 personas.

    baja_frecuencia:
        True cuando la celda contiene menos de 5 casos.
    """

    tabla = tabla.copy()

    tabla["tasa_x100k"] = (
        tabla["casos"] / tabla["poblacion"] * 100000
    )

    tabla["baja_frecuencia"] = tabla["casos"] < 5

    return tabla

def add_department_names(
    tabla: pd.DataFrame,
    poblacion_base: pd.DataFrame
) -> pd.DataFrame:
    """
    Agrega el nombre del departamento a partir del código DP.

    Se utiliza una tabla de referencia territorial del DANE
    para evitar cruces por nombre.
    """

    tabla = tabla.copy()

    departamentos = (
        poblacion_base[["DP", "DPNOM"]]
        .drop_duplicates()
        .copy()
    )

    # Verificar que exista un único nombre por código
    if departamentos["DP"].duplicated().any():
        raise ValueError(
            "Un código DP tiene más de un nombre en la tabla territorial."
        )

    tabla = tabla.merge(
        departamentos,
        on="DP",
        how="left",
        validate="many_to_one"
    )

    if tabla["DPNOM"].isna().any():
        raise ValueError(
            "Hay registros sin nombre de departamento después del cruce."
        )

    tabla = tabla.rename(columns={"DPNOM": "departamento"})

    return tabla

def validate_final_table(tabla: pd.DataFrame) -> None:
    """
    Ejecuta controles de calidad sobre la tabla analítica final.

    Si alguna validación falla, se genera un ValueError.
    Si todas pasan, imprime un resumen de validación.
    """

    llave = ["DP", "AÑO", "sexo", "grupo"]

    # 1. Número esperado de filas
    filas_esperadas = 33 * 10 * 2 * 17

    if len(tabla) != filas_esperadas:
        raise ValueError(
            f"Número de filas incorrecto: "
            f"{len(tabla)} != {filas_esperadas}"
        )

    # 2. Unicidad de la llave
    duplicados = tabla.duplicated(subset=llave).sum()

    if duplicados != 0:
        raise ValueError(
            f"Se encontraron {duplicados} duplicados en la llave {llave}"
        )

    # 3. Cobertura territorial
    if tabla["DP"].nunique() != 33:
        raise ValueError(
            "La tabla no contiene exactamente 33 entidades territoriales."
        )

    # 4. Cobertura temporal
    if tabla["AÑO"].nunique() != 10:
        raise ValueError(
            "La tabla no contiene exactamente 10 años."
        )

    if tabla["AÑO"].min() != 2015 or tabla["AÑO"].max() != 2024:
        raise ValueError(
            "El periodo de la tabla no corresponde a 2015-2024."
        )

    # 5. Sexo
    sexos_esperados = {"Hombre", "Mujer"}

    if set(tabla["sexo"].unique()) != sexos_esperados:
        raise ValueError(
            f"Categorías de sexo inesperadas: {tabla['sexo'].unique()}"
        )

    # 6. Grupos de edad
    grupos_esperados = {
        "(05 a 09)", "(10 a 14)", "(15 a 17)",
        "(18 a 19)", "(20 a 24)", "(25 a 29)",
        "(30 a 34)", "(35 a 39)", "(40 a 44)",
        "(45 a 49)", "(50 a 54)", "(55 a 59)",
        "(60 a 64)", "(65 a 69)", "(70 a 74)",
        "(75 a 79)", "(80 y más)"
    }

    if set(tabla["grupo"].unique()) != grupos_esperados:
        raise ValueError("Los grupos de edad no coinciden con los esperados.")

    # 7. Casos
    if tabla["casos"].isna().any():
        raise ValueError("Existen casos nulos.")

    if (tabla["casos"] < 0).any():
        raise ValueError("Existen valores negativos en casos.")

    # 8. Población
    if tabla["poblacion"].isna().any():
        raise ValueError("Existen valores nulos en población.")

    if (tabla["poblacion"] <= 0).any():
        raise ValueError("Existen poblaciones menores o iguales a cero.")

    # 9. Tasa
    tasa_calculada = tabla["casos"] / tabla["poblacion"] * 100000

    diferencia_tasa = (
        tabla["tasa_x100k"] - tasa_calculada
    ).abs().max()

    if diferencia_tasa > 1e-10:
        raise ValueError(
            f"La tasa no coincide con casos/población. "
            f"Diferencia máxima: {diferencia_tasa}"
        )

    # 10. Nombre de departamento
    if tabla["departamento"].isna().any():
        raise ValueError(
            "Existen departamentos sin nombre."
        )

    # 11. Consistencia de la bandera
    bandera_calculada = tabla["casos"] < 5

    if not tabla["baja_frecuencia"].equals(bandera_calculada):
        raise ValueError(
            "La bandera de baja frecuencia no coincide con casos < 5."
        )

    # 12. Mensaje final
    print("========================================")
    print("VALIDACIÓN DEL PRODUCTO ANALÍTICO")
    print("========================================")
    print(f"Filas: {len(tabla):,}")
    print(f"Departamentos: {tabla['DP'].nunique()}")
    print(f"Años: {tabla['AÑO'].min()}-{tabla['AÑO'].max()}")
    print(f"Sexo: {tabla['sexo'].nunique()} categorías")
    print(f"Grupos de edad: {tabla['grupo'].nunique()}")
    print(f"Casos: {tabla['casos'].sum():,}")
    print(f"Duplicados: {duplicados}")
    print("Validación: OK")