# -*- coding: utf-8 -*-
"""load_data

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16J3Pzx7zBxxFY4LK94Mxz4PHMraQAruE
"""

from pathlib import Path
import sqlite3
import pandas as pd


def load_data(
    tabla: pd.DataFrame,
    processed_dir: Path
) -> tuple[Path, Path]:
    """
    Guarda el producto analítico en CSV y SQLite.
    """

    processed_dir.mkdir(
        parents=True,
        exist_ok=True
    )

    csv_path = (
        processed_dir
        / "suicidios_departamento_edad_sexo_2015_2024.csv"
    )

    db_path = (
        processed_dir
        / "suicidios_departamento_edad_sexo_2015_2024.db"
    )

    # Guardar CSV
    tabla.to_csv(
        csv_path,
        index=False,
        encoding="utf-8-sig"
    )

    # Guardar SQLite
    with sqlite3.connect(db_path) as conn:
        tabla.to_sql(
            "suicidios_analitico",
            conn,
            if_exists="replace",
            index=False
        )

    return csv_path, db_path