# -*- coding: utf-8 -*-
"""modelo

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fTlzQQflIazq_iz8-PEpyVWMapVwdHoT
"""

from pathlib import Path
import sqlite3
import pandas as pd
import statsmodels.formula.api as smf


def cargar_datos(db_path: Path) -> pd.DataFrame:
    """
    Carga desde SQLite el producto analítico generado por el ETL.
    """

    if not db_path.exists():
        raise FileNotFoundError(
            f"No se encontró la base SQLite: {db_path}"
        )

    with sqlite3.connect(db_path) as conn:
        df = pd.read_sql_query(
            """
            SELECT *
            FROM suicidios_analitico
            """,
            conn
        )

    return df


def preparar_datos_modelo(df: pd.DataFrame) -> pd.DataFrame:
    """
    Prepara el producto analítico para el modelado estadístico.
    """

    df = df.copy()

    df["DP"] = df["DP"].astype("category")
    df["AÑO"] = df["AÑO"].astype("category")
    df["sexo"] = df["sexo"].astype("category")
    df["grupo"] = df["grupo"].astype("category")

    if df["casos"].isna().any():
        raise ValueError("Existen casos nulos.")

    if df["poblacion"].isna().any():
        raise ValueError("Existen poblaciones nulas.")

    if (df["poblacion"] <= 0).any():
        raise ValueError(
            "Existen poblaciones menores o iguales a cero."
        )

    return df


def ajustar_poisson(df: pd.DataFrame):
    """
    Ajusta el modelo Poisson de referencia.

    Respuesta:
        casos

    Exposición:
        poblacion

    Predictores:
        sexo, grupo de edad, año y departamento.

    Se incluye la interacción sexo * grupo.
    """

    formula = (
        "casos ~ C(sexo) * C(grupo) "
        "+ C(AÑO) + C(DP)"
    )

    modelo = smf.poisson(
        formula=formula,
        data=df,
        exposure=df["poblacion"]
    )

    resultado = modelo.fit()

    return resultado


def evaluar_dispersion_poisson(resultado) -> float:
    """
    Calcula el índice de dispersión de Pearson:

        chi2_Pearson / grados de libertad residuales

    Valores cercanos a 1 son compatibles con la varianza
    asumida por un modelo Poisson. Valores muy superiores a 1
    indican sobredispersión.
    """

    chi2_pearson = (
        resultado.resid_pearson ** 2
    ).sum()

    dispersion = (
        chi2_pearson / resultado.df_resid
    )

    return float(dispersion)

def validar_temporal(df: pd.DataFrame, año_prueba: int = 2024):
    """
    Entrena el modelo con los años anteriores al año de prueba
    y evalúa la predicción sobre el año reservado.
    """

    df = df.copy()

    # Asegurar que el año sea numérico
    df["AÑO"] = df["AÑO"].astype(int)

    df_train = df[df["AÑO"] < año_prueba].copy()
    df_test = df[df["AÑO"] == año_prueba].copy()

    if df_train.empty:
        raise ValueError("No hay datos de entrenamiento.")

    if df_test.empty:
        raise ValueError(f"No hay datos para el año {año_prueba}.")

    formula = (
        "casos ~ C(sexo) * C(grupo) + AÑO + C(DP)"
    )

    modelo = smf.poisson(
        formula=formula,
        data=df_train,
        exposure=df_train["poblacion"]
    )

    resultado = modelo.fit()

    # Predicciones sobre el año reservado
    df_test["casos_predichos"] = resultado.predict(
        df_test,
        exposure=df_test["poblacion"]
    )

    # Métricas a nivel celda
    error = (
        df_test["casos"] -
        df_test["casos_predichos"]
    )

    mae = error.abs().mean()

    rmse = (
        (error ** 2).mean()
    ) ** 0.5

    correlacion = df_test["casos"].corr(
        df_test["casos_predichos"]
    )

    casos_observados = df_test["casos"].sum()
    casos_predichos = df_test["casos_predichos"].sum()

    return {
        "resultado": resultado,
        "df_test": df_test,
        "mae": float(mae),
        "rmse": float(rmse),
        "correlacion": float(correlacion),
        "casos_observados": int(casos_observados),
        "casos_predichos": float(casos_predichos)
    }

def evaluar_por_departamento(df_test: pd.DataFrame) -> pd.DataFrame:
    """
    Resume los casos observados y predichos por departamento.
    """

    evaluacion = (
        df_test
        .groupby(
            ["DP", "departamento"],
            as_index=False,
            observed=True
        )
        .agg(
            casos_observados=("casos", "sum"),
            casos_predichos=("casos_predichos", "sum")
        )
    )

    evaluacion["error"] = (
        evaluacion["casos_observados"]
        - evaluacion["casos_predichos"]
    )

    evaluacion["error_abs"] = (
        evaluacion["error"].abs()
    )

    evaluacion["error_relativo_pct"] = (
        evaluacion["error"]
        / evaluacion["casos_observados"]
        * 100
    )

    return evaluacion